### ISSUE TITLE
Open source license inquiry

### ISSUE THREAD

**Issue by volt4ire** [mandatoryprogrammer/ChromeGalvanizer#1]
Hey I'm really excited about this extension after hearing about it on [PortSwigger's blog](https://portswigger.net/daily-swig/chrome-galvanizer-released-on-github-to-boost-chrome-extension-security). There's currently no license file for this project though so I was hoping you could post one – hopefully one that's open source (ie: not just "source available"). Github provides a great [brief guide to choosing a license](https://choosealicense.com/). Thanks so much for your time and this awesome project!

**Comment by mandatoryprogrammer** [comment]
I really need to stop forgetting to add a license to these, I'll add MIT - one min

**Comment by mandatoryprogrammer** [comment]
Added in this commit: https://github.com/mandatoryprogrammer/ChromeGalvanizer/commit/8a972b74006122a7da31bafdc9fedbf233a94498

Thanks for filing the issue! If this license doesn't work for your use-case for some reason feel free to file another issue and I can take another look. (I think MIT should be open enough for everyone)

**Comment by volt4ire** [comment]
Awesome thanks so much!
